# Generated by Django 3.2.9 on 2022-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Develop your idea'),
            preserve_default=False,
        ),
    ]
