# Generated by Django 3.2.9 on 2022-02-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220210_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='no category', max_length=255, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
